# Generated by Django 5.0.4 on 2024-05-04 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_salesfile_sales_imoprt_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='imoprt_file',
            new_name='import_file',
        ),
    ]
