version: '3.9'

services:
  frontend:
    build:
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/src
    command: /bin/bash -c "cd fullstack-develop-example-at-django-nextjs && npm run dev"
    ports:
      - "3000:3000"
    tty: true
  backend:
    build:
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/src
    command: /bin/bash -c "./manage.py runserver 0.0.0.0:8000 --settings config.settings.development"
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      TZ: Asia/Tokyo
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8089:8080
    restart: always
    depends_on:
      - db
volumes:
  postgres_volume: 